

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAN_XLVIII_Kristina_Garcia_Francisco.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OrderDBEntities : DbContext
{
    public OrderDBEntities()
        : base("name=OrderDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tblItem> tblItems { get; set; }

    public virtual DbSet<tblOrder> tblOrders { get; set; }

    public virtual DbSet<tblShoppingCart> tblShoppingCarts { get; set; }

    public virtual DbSet<tblUser> tblUsers { get; set; }

}

}

